name: eacli_dart
description: A simple command-line application for eAsistent.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dcli: ^1.17.1
  console: ^4.1.0
  chopper: ^4.0.5
  build_runner: ^2.1.8
  chopper_generator: ^4.0.5
  json_serializable: ^6.1.5
  get_it: ^7.2.0
  hive: ^2.0.6
  tabular: ^0.6.3+1
  intl: ^0.17.0

dev_dependencies:
  lints: ^1.0.0
  json_annotation: ^4.4.0
